name: my_openharmony_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  sliver_tools: ^0.2.12
  flutter_staggered_grid_view: ^0.7.0
  responsive_sizer: ^3.3.1
  flutter_side_menu: ^0.3.2
  auto_size_text: ^3.0.0
  scroll_to_index: ^3.0.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

